"use client";

import type { JSX, ReactNode } from "react";
import { SiteHeader } from "../../components/SiteHeader";
import { SiteFooter } from "../../components/SiteFooter";
import { LegalStyles } from "../legal-styles";
import { useLang } from "../../lib/i18n";

export default function TermsPage(): JSX.Element {
  const { lang } = useLang();
  const L = (fr: ReactNode, en: ReactNode): ReactNode => (lang === "fr" ? fr : en);
  const s = (fr: string, en: string): string => (lang === "fr" ? fr : en);

  return (
    <main className="legal-shell">
      <SiteHeader />

      <div className="legal-viewport">
        <article className="legal-article fade-up">
          <h1>{s("Conditions générales d’utilisation", "Terms of Service")}</h1>
          <p className="legal-updated">{s("Dernière mise à jour : juin 2026", "Last updated: June 2026")}</p>

          <p>
            {L(
              "Bienvenue sur AncreMed. En accédant ou en utilisant notre service, vous acceptez de vous conformer aux présentes Conditions Générales d’Utilisation (CGU).",
              "Welcome to AncreMed. By accessing or using our service, you agree to comply with these Terms of Service."
            )}
          </p>

          <h2>{s("1. Clause de non-responsabilité médicale", "1. Medical disclaimer")}</h2>
          <p className="legal-warning">
            {L(
              <><strong>Attention :</strong> AncreMed est un outil purement informatif et éducatif destiné à la formation académique des étudiants en médecine. Il ne constitue pas un dispositif médical et ne doit en aucun cas être utilisé pour diagnostiquer, traiter ou conseiller un patient réel. Les réponses fournies sont générées par intelligence artificielle à partir d’extraits documentaires et peuvent comporter des erreurs de transcription ou des interprétations erronées. La responsabilité des décisions cliniques incombe exclusivement aux praticiens de santé.</>,
              <><strong>Warning:</strong> AncreMed is a purely informational and educational tool intended for the academic training of medical students. It is not a medical device and must never be used to diagnose, treat, or advise a real patient. The answers provided are generated by artificial intelligence from documentary excerpts and may contain transcription errors or misinterpretations. Responsibility for clinical decisions rests exclusively with healthcare practitioners.</>
            )}
          </p>

          <h2>{s("2. Utilisation du service", "2. Use of the service")}</h2>
          <p>
            {L(
              "Vous vous engagez à ne pas utiliser l’application de manière abusive ou à soumettre des données malveillantes visant à perturber le fonctionnement du moteur sémantique.",
              "You agree not to misuse the application or to submit malicious data intended to disrupt the operation of the semantic engine."
            )}
          </p>

          <h2>{s("3. Propriété intellectuelle & licence", "3. Intellectual property & license")}</h2>
          <p>
            {L(
              "Le code source d’AncreMed est libre et distribué sous licence MIT. Les données cliniques indexées appartiennent à leurs autorités de réglementation respectives (HAS, ANSM).",
              "AncreMed's source code is open and distributed under the MIT license. The indexed clinical data belongs to its respective regulatory authorities (HAS, ANSM)."
            )}
          </p>

          <h2>{s("4. Limites de garantie", "4. Warranty limitations")}</h2>
          <p>
            {L(
              "Le service est fourni « en l’état », sans garantie de disponibilité continue ou d’exactitude absolue des informations fournies par les API de tiers.",
              "The service is provided \"as is\", with no guarantee of continuous availability or absolute accuracy of the information provided by third-party APIs."
            )}
          </p>
        </article>
      </div>

      <SiteFooter />
      <LegalStyles />
    </main>
  );
}
